### ISSUE TITLE
Enhance code

### ISSUE THREAD

**Issue by eznix86** [jcarlosroldan/oink#6]
> Note: This is just a proposal.
- Using function name as path is great, but it has some limitation in terms of flexibility. Like finding specific resources.
- The `Request` object references #4 
- Making a unified validators
- Make the code expressive
- The annotation can be used to generate swagger documentation. related to #5 

```php
<?php

namespace API\Resources;
use Oink\Response;
use Oink\File;

#[Url(path: '/users/{id}', method: "POST")]
function get_user(Request $request, int $id) {

   $request->validate([
      'name': str(...)
      'age': number(...)
   ]);

   return Response::json({});
}

#[Url(path: '/users/{id}/', method: "GET"]
function get_user(Request $request, int $id) {
   
   return Response::json({});
}


#[Url(path: '/users/{name}/', method: "POST"]
function get_image(Request $request, string $name) {
     $request->validate([
      'file': file(...)
   ]);
   File::moveFileTo(...);
   return Response::responseWithFile(...);
}

# in index.php
Oink\serve('endpoints', base_path: '/api');
```

**Comment by jcarlosroldan** [comment]
Thanks! A few comments on this proposal:

The key principle of this repo is to have the least boilerplate possible, which is why I avoided the OOP syntax and the unified validation. Some of these ideas would make sense, as long as the default if not used is a reasonable fallback. For instance, we could use a function attribute to dynamically change the endpoint, but if not set, defaulting to the current behavior.

About endpoints for serving static files, check the gallery example or the part of the docs about routing, there is a way to overcome this limitation adding an extension to the call.

Also, the request object referenced in #4 is for internals, the external parameter management wouldn’t change
